# Generated by Django 4.2.7 on 2024-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaytomorrownews', '0002_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='category', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
